/**
 * LK Digital — 90-Day Content Calendar
 *
 * Days 1-90: 1 post/day (90 posts)
 * Day 91+: 3 posts/week (Mon, Wed, Fri)
 *
 * Content Pillars:
 * P1: Dental Marketing How-Tos (30%)
 * P2: Dentist Business Problems (25%) — from Master Problems List
 * P3: Industry Insights & Trends (20%)
 * P4: Specialty-Specific Guides (15%)
 * P5: Curated Expert Insights (10%) — from Hormozi, Kennedy, Meadows
 *
 * Source Frameworks:
 * - Hormozi Value Equation: Dream Result × Perceived Likelihood ÷ (Time Delay × Effort)
 * - Kennedy Wealth Magnets: Authority, Demonstration, Follow-Up, Be Somebody
 * - Meadows Systems Thinking: Feedback loops, leverage points in dental practices
 */

export interface ContentCalendarEntry {
  day: number;
  pillar: "P1" | "P2" | "P3" | "P4" | "P5";
  slug: string;
  title: string;
  targetKeyword: string;
  category: string;
  problemRef?: string; // Reference to Master Problems List section
  frameworkRef?: string; // Reference to mentor framework
  outline: string[];
  cta: string;
}

export const contentCalendar: ContentCalendarEntry[] = [
  // ===== WEEK 1: Foundation — Establishing Authority =====
  {
    day: 1,
    pillar: "P1",
    slug: "como-dentista-aparecer-primeira-pagina-google",
    title: "Como Fazer Seu Consultório Aparecer na Primeira Página do Google em 2025",
    targetKeyword: "dentista primeira página google",
    category: "SEO",
    outline: [
      "Por que 82% dos pacientes buscam dentistas no Google antes de agendar",
      "Os 3 fatores que o Google usa para ranquear consultórios locais",
      "Google Meu Negócio: o fator #1 que a maioria ignora",
      "SEO on-page: como otimizar seu site para buscas locais",
      "Avaliações: como cada estrela impacta seu posicionamento",
      "Checklist prático: 10 ações para subir no Google esta semana",
    ],
    cta: "Diagnóstico gratuito de visibilidade no Google",
  },
  {
    day: 2,
    pillar: "P2",
    slug: "cadeiras-vazias-consultorio-como-resolver",
    title: "Cadeiras Vazias no Consultório: 7 Causas Que Ninguém Te Conta (e Como Resolver)",
    targetKeyword: "cadeiras vazias consultório odontológico",
    category: "Gestão",
    problemRef: "2.1 Revenue Instability",
    outline: [
      "A matemática das cadeiras vazias: quanto você perde por mês",
      "Causa 1: Dependência de indicações — o modelo que está morrendo",
      "Causa 2: Presença digital inexistente ou desatualizada",
      "Causa 3: Google Maps mal otimizado",
      "Causa 4: Sem sistema de follow-up com leads",
      "Causa 5: Recepção não treinada para converter",
      "Causa 6: Sem campanha ativa de captação",
      "Causa 7: Não aparecer em buscas de IA (ChatGPT, Gemini)",
      "Plano de ação: da cadeira vazia à agenda cheia em 90 dias",
    ],
    cta: "Descubra quantos pacientes você está perdendo",
  },
  {
    day: 3,
    pillar: "P3",
    slug: "inteligencia-artificial-odontologia-2025",
    title: "Como a Inteligência Artificial Está Mudando a Odontologia em 2025",
    targetKeyword: "inteligência artificial odontologia",
    category: "Tendências",
    outline: [
      "IA na busca por dentistas: ChatGPT, Gemini e Perplexity",
      "Como pacientes já usam IA para escolher profissionais",
      "GEO: a nova fronteira do marketing para dentistas",
      "IA no diagnóstico e planejamento odontológico",
      "Chatbots e automação de atendimento",
      "O que fazer AGORA para não ficar para trás",
    ],
    cta: "Saiba se seu consultório aparece em respostas de IA",
  },
  {
    day: 4,
    pillar: "P4",
    slug: "marketing-implantes-dentarios-captar-pacientes",
    title: "Marketing para Implantes Dentários: Como Captar Pacientes de R$5.000 a R$20.000",
    targetKeyword: "marketing implantes dentários",
    category: "Implantodontia",
    problemRef: "Step C — Premium Funnel Implantes",
    outline: [
      "Por que implantes são o procedimento mais lucrativo — e mais difícil de vender",
      "A jornada do paciente de implante: da dor à decisão",
      "Palavras-chave que atraem pacientes prontos para pagar",
      "Landing page para implantes: os 6 elementos obrigatórios",
      "Google Ads vs. SEO para implantodontia",
      "Como comunicar valor sem mostrar antes/depois (CFO)",
      "Funil de nutrição: do lead ao agendamento em 7 dias",
    ],
    cta: "Estratégia personalizada para sua clínica de implantes",
  },
  {
    day: 5,
    pillar: "P5",
    slug: "valor-percebido-dentista-como-cobrar-mais",
    title: "Por Que Pacientes Questionam Seu Preço — e Como Resolver (Equação de Valor)",
    targetKeyword: "como cobrar mais consultório odontológico",
    category: "Estratégia",
    problemRef: "1.1 Having prices challenged",
    frameworkRef: "Hormozi Value Equation: Dream Result × PLOA ÷ (Time × Effort)",
    outline: [
      "A Equação de Valor: por que preço é relativo",
      "Resultado Desejado: o que o paciente realmente quer (não é só o tratamento)",
      "Probabilidade Percebida: como provas e casos aumentam disposição a pagar",
      "Tempo: por que rapidez no atendimento justifica preço premium",
      "Esforço: quanto menos o paciente precisa fazer, mais ele paga",
      "Aplicação prática: 5 formas de aumentar o valor percebido sem baixar o preço",
      "Case: como um implantodontista passou de R$3k para R$12k por procedimento",
    ],
    cta: "Diagnóstico gratuito do posicionamento de valor",
  },
  {
    day: 6,
    pillar: "P1",
    slug: "google-maps-dentista-como-aparecer-top-3",
    title: "Google Maps para Dentistas: 10 Passos Para Aparecer no Top 3 da Sua Região",
    targetKeyword: "Google Maps dentista como aparecer",
    category: "Google Maps",
    outline: [
      "Por que o 'pacote local' do Google Maps é ouro para dentistas",
      "Passo 1: Verificar e otimizar seu perfil do Google Meu Negócio",
      "Passo 2: Categorias corretas (principal + secundárias)",
      "Passo 3: Fotos profissionais que convertem",
      "Passo 4: Descrição otimizada com palavras-chave locais",
      "Passo 5: Horários e informações atualizadas",
      "Passo 6: Posts semanais no perfil",
      "Passo 7: Gestão ativa de avaliações",
      "Passo 8: Perguntas e respostas otimizadas",
      "Passo 9: Citações NAP consistentes",
      "Passo 10: Schema markup no seu site",
    ],
    cta: "Auditoria gratuita do seu Google Maps",
  },
  {
    day: 7,
    pillar: "P2",
    slug: "leads-nao-aparecem-consulta-no-show-dentista",
    title: "Por Que Seus Leads Não Aparecem na Consulta (e o Sistema Anti-No-Show)",
    targetKeyword: "no show paciente dentista como evitar",
    category: "Conversão",
    problemRef: "4.2 Leads forget the appointment → no-shows",
    outline: [
      "O custo real de um no-show: R$ que você nunca recupera",
      "As 5 razões pelas quais leads marcam e não aparecem",
      "O Sistema Anti-No-Show: 4 camadas de prevenção",
      "Confirmação em múltiplos canais (WhatsApp + SMS + e-mail)",
      "Nutrição pré-consulta: 3 mensagens que reduzem no-shows em 60%",
      "Comprometimento financeiro: taxa de agendamento funciona?",
      "Automação: como implementar sem trabalho manual",
    ],
    cta: "Implemente o Sistema Anti-No-Show no seu consultório",
  },

  // ===== WEEK 2: Building Trust & Authority =====
  {
    day: 8,
    pillar: "P5",
    slug: "dentista-autoridade-como-ser-referencia",
    title: "Como Se Tornar O Dentista Mais Respeitado da Sua Cidade (Princípio 'Be Somebody')",
    targetKeyword: "dentista autoridade referência cidade",
    category: "Posicionamento",
    problemRef: "5. Feeling inferior to competitors / fear of losing relevance",
    frameworkRef: "Kennedy Wealth Magnet 8: Be Somebody / Be an Expert Somebody",
    outline: [
      "A diferença entre ser bom e ser percebido como o melhor",
      "O princípio 'Be Somebody': por que especialização vence generalismo",
      "Como construir autoridade em 90 dias sem virar influencer",
      "Google Reviews: o indicador #1 de autoridade percebida",
      "Conteúdo que demonstra expertise (sem violar o CFO)",
      "Palestras, entrevistas e parcerias estratégicas",
      "O efeito composto: como autoridade atrai pacientes premium",
    ],
    cta: "Descubra como construir sua autoridade digital",
  },
  {
    day: 9,
    pillar: "P1",
    slug: "avaliacoes-google-dentista-como-conseguir",
    title: "Como Conseguir 100+ Avaliações 5 Estrelas no Google (Sistema Comprovado para Dentistas)",
    targetKeyword: "avaliações Google dentista como conseguir",
    category: "Reputação",
    problemRef: "1.2 No system to consistently generate 5-star reviews",
    outline: [
      "Por que avaliações são o fator #1 de decisão para pacientes",
      "O momento perfeito para pedir avaliação (timing é tudo)",
      "Script de solicitação: o que dizer sem ser inconveniente",
      "QR Code + link direto: removendo atrito do processo",
      "Automação via WhatsApp: solicitar no pós-consulta",
      "Como responder avaliações negativas (sem violar o CFO)",
      "Meta: de 10 para 100 avaliações em 90 dias",
    ],
    cta: "Implemente o Reviews Boost System no seu consultório",
  },
  {
    day: 10,
    pillar: "P2",
    slug: "recepcao-consultorio-perdendo-pacientes",
    title: "Sua Recepção Está Perdendo Pacientes? 8 Erros Que Custam Milhares Por Mês",
    targetKeyword: "recepção consultório odontológico treinamento",
    category: "Gestão",
    problemRef: "2.4 Untrained front desk causing sales leakage",
    outline: [
      "A recepção é o ponto de maior vazamento de receita",
      "Erro 1: Não responder WhatsApp em menos de 5 minutos",
      "Erro 2: Dar preço por telefone sem gerar valor",
      "Erro 3: Não ter script de agendamento",
      "Erro 4: Não confirmar consultas 24h e 3h antes",
      "Erro 5: Não fazer follow-up com quem não agendou",
      "Erro 6: Tom de voz errado — frio ou excessivamente informal",
      "Erro 7: Não qualificar o lead antes de agendar",
      "Erro 8: Não registrar motivos de cancelamento",
      "Template: script completo de atendimento para recepção",
    ],
    cta: "Treinamento de conversão para sua equipe",
  },
  {
    day: 11,
    pillar: "P4",
    slug: "marketing-ortodontia-invisalign-captar-pacientes",
    title: "Marketing para Ortodontia e Invisalign: Como Atrair Pacientes Que Valorizam Qualidade",
    targetKeyword: "marketing ortodontia invisalign",
    category: "Ortodontia",
    problemRef: "Step C — Premium Funnel Invisalign",
    outline: [
      "O mercado de ortodontia premium no Brasil",
      "Por que competir por preço é uma corrida para o fundo",
      "Posicionamento: expertise clínica vs. preço baixo",
      "Simulação 3D como ferramenta de conversão",
      "Conteúdo educativo: o funil do paciente de Invisalign",
      "Google Ads para ortodontia: palavras-chave que convertem",
      "Upsell: clareamento + resina estética + lentes",
    ],
    cta: "Estratégia personalizada para ortodontia",
  },
  {
    day: 12,
    pillar: "P3",
    slug: "regulamentacao-cfo-publicidade-odontologica-2025",
    title: "Publicidade Odontológica em 2025: Tudo Que o CFO Permite e Proíbe",
    targetKeyword: "publicidade odontológica CFO regras 2025",
    category: "Compliance",
    outline: [
      "As resoluções do CFO sobre publicidade: visão geral atualizada",
      "O que PODE: lista completa de práticas permitidas",
      "O que NÃO PODE: antes/depois, promessas, preços",
      "Redes sociais: regras específicas para Instagram e TikTok",
      "Google Ads: compliance em anúncios pagos",
      "Penalidades: o que acontece se violar",
      "Como fazer marketing efetivo dentro das regras",
    ],
    cta: "Marketing em conformidade com o CFO",
  },
  {
    day: 13,
    pillar: "P5",
    slug: "oferta-irresistivel-dentista-como-criar",
    title: "Como Criar uma Oferta Irresistível Para Seu Consultório (Sem Dar Desconto)",
    targetKeyword: "oferta irresistível consultório odontológico",
    category: "Estratégia",
    frameworkRef: "Hormozi $100M Offers: Grand Slam Offer framework",
    outline: [
      "Por que desconto destrói o valor percebido do seu trabalho",
      "O que é uma 'Grand Slam Offer' (e por que funciona)",
      "Os 4 componentes de uma oferta irresistível para dentistas",
      "Exemplos: avaliação premium + planejamento 3D + simulação",
      "Como empacotar valor sem reduzir preço",
      "Garantias que removem risco do paciente",
      "Bônus que aumentam valor percebido (pós-operatório VIP, etc.)",
    ],
    cta: "Crie sua oferta premium",
  },
  {
    day: 14,
    pillar: "P1",
    slug: "whatsapp-business-dentista-converter-leads",
    title: "WhatsApp Business para Dentistas: Como Converter 3x Mais Leads em Pacientes",
    targetKeyword: "WhatsApp Business dentista conversão",
    category: "Conversão",
    problemRef: "2.3 No automated WhatsApp nurturing sequence",
    outline: [
      "Por que 90% dos leads preferem WhatsApp a ligação",
      "Configuração profissional: perfil, catálogo, mensagens automáticas",
      "Templates de primeira mensagem que geram resposta",
      "Sequência de nutrição em 4 dias",
      "Automação: chatbot vs. atendimento humano",
      "Métricas: taxa de resposta, taxa de agendamento, no-show",
      "Integração com CRM e calendário",
    ],
    cta: "Automatize seu WhatsApp",
  },

  // ===== WEEK 3: Problems & Solutions =====
  {
    day: 15,
    pillar: "P2",
    slug: "dentista-leads-nao-podem-pagar",
    title: "Seus Leads Não Podem Pagar? Como Atrair Pacientes de Alto Valor",
    targetKeyword: "dentista atrair pacientes alto valor",
    category: "Captação",
    problemRef: "2.2 Leads who can't afford the treatment",
    outline: [
      "O problema: gastar com marketing e atrair quem só quer preço",
      "Segmentação: como filtrar leads por poder aquisitivo",
      "Posicionamento premium: sinais que atraem pacientes de valor",
      "Google Ads: palavras-chave de alta intenção vs. orçamento",
      "Landing pages que pré-qualificam antes do WhatsApp",
      "Lead scoring: classificar leads automaticamente",
    ],
    cta: "Atraia pacientes premium",
  },
  {
    day: 16,
    pillar: "P4",
    slug: "marketing-estetica-dental-lentes-contato",
    title: "Marketing para Estética Dental: Como Captar Pacientes de Lentes de Contato e Clareamento",
    targetKeyword: "marketing estética dental lentes de contato",
    category: "Estética",
    outline: [
      "O boom da estética dental no Brasil: números e tendências",
      "O perfil do paciente de estética: aspiracional e visual",
      "Instagram como canal principal (dentro das regras do CFO)",
      "Google Ads para estética: termos que convertem",
      "Portfolio visual: como mostrar resultados sem violar regulações",
      "Harmonização orofacial: o serviço complementar que cresce 200%/ano",
    ],
    cta: "Estratégia para estética dental premium",
  },
  {
    day: 17,
    pillar: "P3",
    slug: "custo-por-lead-dentista-quanto-pagar",
    title: "Quanto Custa um Lead Para Dentistas? Benchmarks Reais por Especialidade",
    targetKeyword: "custo por lead dentista preço",
    category: "Dados",
    outline: [
      "O que é custo por lead e por que é a métrica mais importante",
      "Benchmark por especialidade: implantes, ortodontia, estética, geral",
      "Benchmark por cidade: SP, RJ, BH, Curitiba, cidades médias",
      "Google Ads vs. Meta Ads: onde o CPL é menor (e quando)",
      "Como reduzir seu CPL sem reduzir volume",
      "A métrica que importa mais que CPL: custo por paciente convertido",
    ],
    cta: "Saiba quanto deveria estar pagando por lead",
  },
  {
    day: 18,
    pillar: "P5",
    slug: "pensamento-sistemico-consultorio-odontologico",
    title: "Pensamento Sistêmico Para Dentistas: Por Que Seu Consultório Não Cresce (e Como Desbloquear)",
    targetKeyword: "gestão consultório odontológico crescimento",
    category: "Gestão",
    frameworkRef: "Meadows Thinking in Systems: feedback loops, leverage points",
    outline: [
      "Seu consultório é um sistema — e sistemas têm gargalos",
      "Loops de reforço: quando marketing gera mais indicações que geram mais marketing",
      "Loops de equilíbrio: o que impede seu crescimento mesmo investindo",
      "Pontos de alavancagem: as 3 mudanças que destravam 80% do crescimento",
      "Alavanca 1: visibilidade digital (o topo do funil)",
      "Alavanca 2: conversão da recepção (o meio do funil)",
      "Alavanca 3: retenção e reativação (o fundo do funil)",
      "Como diagnosticar qual gargalo está travando seu consultório",
    ],
    cta: "Diagnóstico de gargalos do seu consultório",
  },
  {
    day: 19,
    pillar: "P1",
    slug: "site-consultorio-odontologico-elementos-essenciais",
    title: "Site Para Consultório Odontológico: Os 12 Elementos Que Convertem Visitantes em Pacientes",
    targetKeyword: "site consultório odontológico elementos",
    category: "Website",
    problemRef: "1.1 Old or low-quality website that damages credibility",
    outline: [
      "Por que seu site é mais importante que seu cartão de visitas",
      "Elemento 1: headline clara com proposta de valor",
      "Elemento 2: prova social acima da dobra",
      "Elemento 3: WhatsApp fixo (botão flutuante)",
      "Elemento 4: especialidades com páginas dedicadas",
      "Elemento 5: depoimentos reais com nome e foto",
      "Elemento 6: fotos profissionais do consultório",
      "Elemento 7: bio do dentista com credenciais",
      "Elemento 8: formulário simples de contato",
      "Elemento 9: blog com conteúdo educativo",
      "Elemento 10: schema markup e SEO técnico",
      "Elemento 11: velocidade de carregamento",
      "Elemento 12: design responsivo (mobile-first)",
    ],
    cta: "Auditoria gratuita do seu site",
  },
  {
    day: 20,
    pillar: "P2",
    slug: "dentista-depende-indicacao-como-mudar",
    title: "Você Ainda Depende de Indicação? Por Que Isso Está Matando Seu Consultório",
    targetKeyword: "dentista depende indicação como captar pacientes",
    category: "Captação",
    problemRef: "2.1 Reliance on word-of-mouth",
    outline: [
      "Indicação é ótima — mas não é um sistema",
      "O risco: o que acontece quando as indicações secam",
      "A transição: de indicação para captação ativa (sem perder indicações)",
      "Canal 1: SEO local — pacientes que já estão buscando",
      "Canal 2: Google Ads — pacientes prontos para agendar",
      "Canal 3: Conteúdo — pacientes que ainda estão pesquisando",
      "O sistema ideal: indicação + digital trabalhando juntos",
    ],
    cta: "Monte seu sistema de captação digital",
  },
  {
    day: 21,
    pillar: "P3",
    slug: "marketing-digital-dentista-roi-retorno-investimento",
    title: "ROI do Marketing Digital Para Dentistas: Como Calcular e Quando Esperar Retorno",
    targetKeyword: "ROI marketing digital dentista",
    category: "Dados",
    outline: [
      "O que é ROI e por que dentistas precisam rastrear",
      "Fórmula simples: (Receita gerada - Investimento) / Investimento",
      "Benchmarks: ROI médio por canal (Google, Meta, SEO)",
      "Quando esperar retorno: timeline realista por canal",
      "Google Ads: retorno em 2-4 semanas",
      "SEO: retorno em 3-6 meses (mas crescente)",
      "Como montar um dashboard simples para acompanhar",
    ],
    cta: "Calcule o ROI potencial do seu consultório",
  },

  // ===== WEEKS 4-6: Deep Dives =====
  {
    day: 22,
    pillar: "P5",
    slug: "follow-up-pacientes-sistema-dentista",
    title: "O Dinheiro Está no Follow-Up: Como 80% dos Dentistas Perdem Pacientes por Falta de Acompanhamento",
    targetKeyword: "follow up pacientes dentista sistema",
    category: "Conversão",
    problemRef: "2.3 No multi-step follow-up system",
    frameworkRef: "Kennedy Wealth Magnet 12: Follow-Up + Why is Follow-Up So Magnetic?",
    outline: [
      "A estatística que muda tudo: 80% das vendas acontecem entre o 5º e 12º contato",
      "Por que dentistas desistem no 1º ou 2º contato",
      "O sistema de follow-up em 7 toques para odontologia",
      "Templates de mensagens para cada etapa",
      "Automação: como o sistema trabalha enquanto você atende",
      "Follow-up pós-consulta: transformando pacientes em promotores",
    ],
    cta: "Implemente follow-up automatizado",
  },
  {
    day: 23,
    pillar: "P4",
    slug: "marketing-odontopediatria-captar-pais",
    title: "Marketing para Odontopediatria: Como Captar Pais Que Procuram o Melhor Dentista Para Seus Filhos",
    targetKeyword: "marketing odontopediatria dentista infantil",
    category: "Odontopediatria",
    outline: [
      "O perfil do pai/mãe que busca odontopediatra: medo e exigência",
      "Palavras-chave que mães digitam no Google",
      "Conteúdo que gera confiança: medo do dentista, primeira consulta",
      "Google Meu Negócio: fotos do ambiente infantil convertem",
      "Instagram para odontopediatria: o que funciona (e o que o CFO proíbe)",
      "Retenção: programa de retorno semestral",
    ],
    cta: "Atraia mais famílias para seu consultório",
  },
  {
    day: 24,
    pillar: "P2",
    slug: "concorrente-dominando-google-como-competir",
    title: "Seu Concorrente Domina o Google? 5 Estratégias Para Ultrapassá-lo em 90 Dias",
    targetKeyword: "concorrente dentista Google como superar",
    category: "SEO",
    problemRef: "1.3 Competitors dominating local search",
    outline: [
      "Análise competitiva: como descobrir o que o concorrente está fazendo",
      "Estratégia 1: vencer no Google Maps (mais rápido que SEO)",
      "Estratégia 2: Google Ads para aparecer acima do resultado orgânico",
      "Estratégia 3: conteúdo que rouba featured snippets",
      "Estratégia 4: avaliações — superar em volume e qualidade",
      "Estratégia 5: presença em IA — o canal que ele ainda não domina",
    ],
    cta: "Análise competitiva gratuita da sua região",
  },
  {
    day: 25,
    pillar: "P1",
    slug: "instagram-dentista-conteudo-que-converte",
    title: "Instagram para Dentistas: 15 Ideias de Conteúdo Que Realmente Convertem Pacientes",
    targetKeyword: "Instagram dentista conteúdo ideias",
    category: "Redes Sociais",
    problemRef: "1.1 Irregular posting on social media",
    outline: [
      "Por que a maioria dos dentistas erra no Instagram (e como acertar)",
      "5 tipos de conteúdo educativo que geram confiança",
      "5 tipos de prova social que convertem seguidores em pacientes",
      "5 tipos de conteúdo de bastidores que humanizam",
      "Frequência ideal: qualidade vs. quantidade",
      "Hashtags e SEO no Instagram: como ser descoberto",
      "Call-to-action: do post ao WhatsApp",
    ],
    cta: "Gestão de redes sociais para dentistas",
  },
  {
    day: 26,
    pillar: "P3",
    slug: "tendencias-marketing-odontologico-2025",
    title: "7 Tendências do Marketing Odontológico em 2025 Que Vão Definir Quem Cresce",
    targetKeyword: "tendências marketing odontológico 2025",
    category: "Tendências",
    outline: [
      "Tendência 1: IA respondendo perguntas de pacientes (GEO)",
      "Tendência 2: Vídeo curto (Reels/TikTok) como canal de confiança",
      "Tendência 3: Automação de WhatsApp e chatbots",
      "Tendência 4: SEO hiperlocal (bairro, não apenas cidade)",
      "Tendência 5: Pacientes pesquisando tratamentos antes da consulta",
      "Tendência 6: Review management como diferencial competitivo",
      "Tendência 7: Personalização na comunicação via dados",
    ],
    cta: "Prepare seu consultório para 2025",
  },
  {
    day: 27,
    pillar: "P5",
    slug: "dentista-medo-investir-marketing-como-superar",
    title: "Medo de Investir em Marketing? Como Dentistas Superam o Bloqueio e Crescem",
    targetKeyword: "dentista medo investir marketing",
    category: "Mentalidade",
    problemRef: "4. Financial Fears — Vou gastar dinheiro e não vai ter retorno",
    frameworkRef: "Kennedy Wealth Magnet 5: No Fear / Hormozi: reducing risk perception",
    outline: [
      "O medo real: 'já tentei e não funcionou'",
      "Por que a maioria das experiências anteriores falhou (agência genérica)",
      "Reframe: marketing não é custo — é aquisição de pacientes",
      "A matemática simples: 1 implante paga meses de marketing",
      "Como reduzir risco: garantias, testes pequenos, escala gradual",
      "Histórias reais: dentistas que superaram o medo e transformaram seus consultórios",
    ],
    cta: "Diagnóstico sem risco — gratuito e sem compromisso",
  },
  {
    day: 28,
    pillar: "P1",
    slug: "landing-page-dentista-alta-conversao",
    title: "Landing Page Para Dentistas: Como Criar Páginas Que Convertem 3x Mais Agendamentos",
    targetKeyword: "landing page dentista conversão",
    category: "Conversão",
    problemRef: "2.5 No landing page optimized for conversion",
    outline: [
      "Landing page vs. site institucional: quando usar cada um",
      "A estrutura de alta conversão em 7 seções",
      "Seção 1: headline com resultado + dor + especialidade",
      "Seção 2: prova social imediata",
      "Seção 3: como funciona (3 passos)",
      "Seção 4: benefícios específicos do tratamento",
      "Seção 5: depoimentos com contexto",
      "Seção 6: FAQ que remove objeções",
      "Seção 7: CTA final com urgência",
      "Erros comuns que matam conversão",
    ],
    cta: "Landing page profissional para seu consultório",
  },

  // ===== WEEKS 4-6 continued (days 29-42) =====
  { day: 29, pillar: "P2", slug: "agenda-caotica-dentista-como-organizar", title: "Agenda Caótica? Como Organizar Seu Consultório Para Maximizar Faturamento", targetKeyword: "organizar agenda consultório odontológico", category: "Gestão", problemRef: "2.4 Bad agenda management / chaos in scheduling", outline: ["O custo oculto da desorganização", "Princípio: horários nobres para procedimentos de alto valor", "Como calcular o valor/hora de cada procedimento", "Blocos de agenda: separando urgências de procedimentos planejados", "Ferramentas de agendamento online que funcionam", "Automação de lembretes e confirmações"], cta: "Otimize sua agenda" },
  { day: 30, pillar: "P4", slug: "marketing-endodontia-emergencia-dental", title: "Marketing para Endodontia: Como Captar Pacientes de Emergência e Tratamento de Canal", targetKeyword: "marketing endodontia tratamento canal", category: "Endodontia", outline: ["O paciente de endodontia: urgência + medo", "Palavras-chave de emergência: como aparecer na hora certa", "Google Ads para termos de urgência", "Google Maps: o primeiro resultado que o paciente vê com dor", "Conteúdo educativo: desmistificando o tratamento de canal", "Conversão rápida: do clique ao agendamento em minutos"], cta: "Capte pacientes de endodontia" },
  { day: 31, pillar: "P1", slug: "seo-local-dentista-bairro-regiao", title: "SEO Hiperlocal Para Dentistas: Como Dominar Buscas no Seu Bairro", targetKeyword: "SEO local dentista bairro", category: "SEO", outline: ["Por que 'dentista em [bairro]' converte mais que 'dentista em [cidade]'", "Criando páginas para cada região que você atende", "Google Maps: raio de atuação e otimização por bairro", "Conteúdo localizado que ranqueia rápido", "Citações locais: diretórios e parceiros regionais", "Casos: dentistas que dominam micro-regiões"], cta: "Domine as buscas no seu bairro" },
  { day: 32, pillar: "P5", slug: "demonstracao-resultados-dentista-marketing", title: "Demonstração É a Nova Publicidade: Como Mostrar (Não Apenas Dizer) Que Você É o Melhor", targetKeyword: "demonstrar resultados dentista marketing", category: "Posicionamento", frameworkRef: "Kennedy Wealth Magnet 11: Demonstration", outline: ["Por que 'somos os melhores' não convence ninguém", "O poder da demonstração: mostrar > dizer", "5 formas de demonstrar expertise sem violar o CFO", "Vídeos educativos: mostrando competência técnica", "Dados e métricas como prova (avaliações, tempo de experiência)", "Cases contextualizados: o problema, a solução, o resultado"], cta: "Construa sua estratégia de demonstração" },
  { day: 33, pillar: "P2", slug: "dentista-pacientes-somem-depois-primeira-consulta", title: "Por Que Pacientes Somem Depois da Primeira Consulta (e Como Trazê-los de Volta)", targetKeyword: "paciente some depois primeira consulta dentista", category: "Retenção", problemRef: "3.1 Patients disappearing after the first visit", outline: ["Os dados: quanto custa adquirir vs. reter um paciente", "As 5 razões pelas quais pacientes não voltam", "Sistema de reativação: recuperando pacientes inativos", "WhatsApp automático: lembretes de retorno semestral", "Programa VIP: criando fidelidade a longo prazo", "E-mail/SMS de follow-up pós-tratamento"], cta: "Reative seus pacientes inativos" },
  { day: 34, pillar: "P3", slug: "google-ads-dentista-erros-que-desperdicam-dinheiro", title: "8 Erros em Google Ads Que Fazem Dentistas Desperdiçar R$3.000/Mês (Ou Mais)", targetKeyword: "Google Ads dentista erros desperdiçar dinheiro", category: "Ads", outline: ["Erro 1: não usar palavras-chave negativas", "Erro 2: landing page genérica (ou pior, o site institucional)", "Erro 3: ignorar extensões de anúncio", "Erro 4: não separar campanhas por serviço", "Erro 5: orçamento espalhado demais", "Erro 6: não rastrear conversões", "Erro 7: copiar o que o concorrente faz", "Erro 8: desistir antes de otimizar"], cta: "Auditoria gratuita de Google Ads" },
  { day: 35, pillar: "P4", slug: "marketing-periodontia-educar-pacientes", title: "Marketing para Periodontia: Como Educar Pacientes Que Nem Sabem Que Precisam de Você", targetKeyword: "marketing periodontia pacientes", category: "Periodontia", outline: ["O desafio: 50% dos adultos têm doença periodontal e não sabem", "Conteúdo educativo como funil de captação", "SEO para sintomas: gengiva sangrando, retração, mau hálito", "Parcerias com clínicos gerais para referência", "Como transformar consulta de avaliação em tratamento recorrente", "Programa de manutenção periodontal como receita recorrente"], cta: "Estratégia para periodontia" },

  // Days 36-42
  { day: 36, pillar: "P1", slug: "meta-ads-dentista-facebook-instagram", title: "Meta Ads Para Dentistas: Como Criar Campanhas no Facebook e Instagram Que Geram Pacientes", targetKeyword: "Facebook Ads Instagram Ads dentista", category: "Ads", outline: ["Quando usar Meta Ads vs. Google Ads", "Estrutura de campanha para odontologia", "Criativos que convertem (respeitando o CFO)", "Segmentação: interesses, localização, lookalike", "Retargeting: quem visitou seu site mas não agendou", "Orçamento mínimo recomendado por especialidade"], cta: "Campanhas de Meta Ads para dentistas" },
  { day: 37, pillar: "P2", slug: "dentista-cobrar-mais-sem-perder-pacientes", title: "Como Cobrar Mais Sem Perder Pacientes: Estratégias de Precificação Para Dentistas", targetKeyword: "dentista cobrar mais precificação", category: "Gestão", problemRef: "2.1 Underpricing due to fear of losing clients", outline: ["O medo de cobrar: por que dentistas subestimam seu trabalho", "Precificação baseada em valor vs. baseada em custo", "Como aumentar preço gradualmente sem perder base", "Comunicação de valor: o que dizer quando questionam o preço", "Pacotes e bundles que aumentam ticket médio", "Financiamento como ferramenta de conversão"], cta: "Reposicione seu preço" },
  { day: 38, pillar: "P5", slug: "escassez-urgencia-consultorio-odontologico", title: "Escassez e Urgência Ética: Como Usar Exclusividade Para Lotar Sua Agenda", targetKeyword: "escassez urgência marketing dentista", category: "Estratégia", frameworkRef: "Hormozi $100M Offers: Scarcity, Urgency, Bonuses, Guarantees", outline: ["A psicologia da escassez: por que funciona", "Escassez real vs. fabricada (ética primeiro)", "Exclusividade territorial: modelo que gera urgência genuína", "Vagas limitadas por mês: quando faz sentido", "Promoções com deadline: os formatos que funcionam para dentistas", "Como comunicar escassez sem parecer desespero"], cta: "Aplique escassez ética" },
  { day: 39, pillar: "P3", slug: "chatgpt-recomendando-dentistas-como-aparecer", title: "O ChatGPT Está Recomendando Dentistas — Seu Consultório Está Entre Eles?", targetKeyword: "ChatGPT recomenda dentista como aparecer", category: "GEO", outline: ["Teste: pergunte ao ChatGPT 'melhor dentista em [sua cidade]'", "Como o ChatGPT escolhe quais dentistas recomendar", "Os fatores que influenciam: presença digital, avaliações, conteúdo", "3 ações para ser citado por IAs em 60 dias", "Schema markup que ajuda IAs a entender seu conteúdo", "O futuro: quando 40% das buscas serão feitas por IA"], cta: "Apareça em respostas de IA" },
  { day: 40, pillar: "P1", slug: "email-marketing-dentista-reativacao-pacientes", title: "E-mail Marketing Para Dentistas: Como Reativar Pacientes e Gerar Retorno Semestral", targetKeyword: "email marketing dentista reativação", category: "Retenção", problemRef: "4.4 No reactivation campaigns for inactive patients", outline: ["Por que e-mail marketing ainda funciona (e bem) para dentistas", "Segmentação: pacientes ativos, inativos, prospects", "Sequência de reativação em 5 e-mails", "Newsletter mensal: conteúdo que mantém você 'top of mind'", "Automação: lembrete de retorno semestral", "Templates prontos para copiar e usar"], cta: "Reative sua base de pacientes" },
  { day: 41, pillar: "P4", slug: "marketing-harmonizacao-orofacial-captar-pacientes", title: "Marketing para Harmonização Orofacial: Como Captar Pacientes de Estética Premium", targetKeyword: "marketing harmonização orofacial", category: "Estética", problemRef: "Step C — Premium Funnel Harmonização Facial", outline: ["O mercado de HOF no Brasil: crescimento e oportunidade", "Posicionamento: resultado natural vs. exagero", "O perfil do paciente: motivações emocionais e estéticas", "Conteúdo visual no Instagram (dentro do CFO)", "Google Ads para harmonização: termos que convertem", "Simulação digital como ferramenta de conversão", "Upsell: botulínica + skinbooster + bioestimulador"], cta: "Estratégia para harmonização orofacial" },
  { day: 42, pillar: "P2", slug: "dentista-burnout-trabalho-demais-como-resolver", title: "Burnout no Consultório: Como Dentistas Podem Trabalhar Menos e Faturar Mais", targetKeyword: "dentista burnout trabalhar menos faturar mais", category: "Gestão", problemRef: "6. Constant stress and burnout / Dream: business runs without chaos", frameworkRef: "Hormozi: Reducing Effort & Sacrifice", outline: ["A epidemia silenciosa: burnout entre dentistas brasileiros", "Por que trabalhar mais horas não é a resposta", "Princípio: mais procedimentos de alto valor, menos volume baixo", "Automação: o que pode rodar sem você", "Delegação: treinando equipe para a recepção vender", "O modelo ideal: 4 dias/semana, agenda premium", "Caso real: de 50h/semana para 32h com mais faturamento"], cta: "Redesenhe sua operação" },

  // ===== WEEKS 7-9: Scaling & Advanced =====
  { day: 43, pillar: "P1", slug: "crm-dentista-gestao-pacientes-leads", title: "CRM Para Dentistas: Como Gerenciar Leads e Pacientes Sem Perder Nenhum", targetKeyword: "CRM dentista gestão pacientes", category: "Ferramentas", problemRef: "2.4 No client relationship system (CRM)", outline: ["O que é CRM e por que todo consultório precisa de um", "As 3 funções essenciais: captação, conversão, retenção", "CRMs recomendados para consultórios (simples e acessíveis)", "Pipeline de leads: do primeiro contato ao agendamento", "Automação: follow-up, lembretes, reativação", "Métricas para acompanhar no dashboard"], cta: "Implemente CRM no seu consultório" },
  { day: 44, pillar: "P5", slug: "atracao-riqueza-dentista-mentalidade-crescimento", title: "Mentalidade de Abundância: O Que Separa Dentistas Que Faturam R$50k Dos Que Faturam R$200k/Mês", targetKeyword: "dentista mentalidade crescimento faturamento", category: "Mentalidade", frameworkRef: "Kennedy Wealth Magnet 2: Unequivocal Belief in Abundance", outline: ["Mentalidade de escassez vs. abundância na odontologia", "Por que dentistas talentosos ficam presos no mesmo faturamento", "O princípio: pare de comprar narrativas negativas sobre o mercado", "Como dentistas de sucesso pensam diferente sobre marketing", "Investir em crescimento: custo vs. investimento com retorno", "Ações práticas: 5 mudanças de mentalidade que destravam receita"], cta: "Desbloqueie seu crescimento" },
  { day: 45, pillar: "P2", slug: "dentista-branding-marca-premium", title: "Branding Para Dentistas: Como Construir Uma Marca Que Cobra Premium e Atrai Pacientes de Valor", targetKeyword: "branding dentista marca premium", category: "Posicionamento", problemRef: "1.1 Lack of strong brand identity", outline: ["A diferença entre ter um logo e ter uma marca", "Identidade visual: o que transmite 'premium' vs. 'genérico'", "Tom de voz: como se comunicar em cada canal", "Consistência: site + redes + Google Maps + consultório", "Case: rebranding que aumentou ticket médio em 40%", "Checklist: os 8 elementos de uma marca odontológica forte"], cta: "Eleve sua marca" },
  { day: 46, pillar: "P3", slug: "tiktok-reels-dentista-vale-a-pena", title: "TikTok e Reels Para Dentistas: Vale a Pena? O Que Funciona e o Que o CFO Proíbe", targetKeyword: "TikTok Reels dentista", category: "Redes Sociais", outline: ["O cenário: pacientes cada vez mais jovens usam TikTok para decidir", "O que funciona para dentistas: conteúdo educativo curto", "O que o CFO proíbe: antes/depois, promessas, preços", "Formatos que geram engajamento sem violar regulações", "Frequência e consistência: quanto postar", "ROI: TikTok traz pacientes ou só seguidores?"], cta: "Estratégia de vídeo para dentistas" },
  { day: 47, pillar: "P4", slug: "marketing-protese-dentaria-pacientes-idosos", title: "Marketing para Prótese Dentária: Como Alcançar Pacientes que Precisam de Reabilitação Oral", targetKeyword: "marketing prótese dentária reabilitação oral", category: "Prótese", outline: ["O perfil do paciente de prótese: necessidade + vergonha", "Linguagem empática: como falar sobre prótese sem estigma", "Google Ads para termos de reabilitação oral", "Conteúdo educativo: tipos de prótese, processo, resultados", "Google Maps: o canal principal para este público", "Financiamento: removendo a barreira do preço"], cta: "Capte pacientes de prótese" },
  { day: 48, pillar: "P1", slug: "schema-markup-dentista-seo-tecnico", title: "Schema Markup Para Dentistas: O SEO Técnico Que 95% Dos Consultórios Ignoram", targetKeyword: "schema markup dentista SEO técnico", category: "SEO", outline: ["O que é schema markup e por que o Google ama", "Os 5 schemas essenciais para consultórios odontológicos", "LocalBusiness/Dentist schema: implementação passo a passo", "FAQPage schema: suas perguntas aparecendo no Google", "HowTo schema: procedimentos passo a passo", "Review schema: estrelas nos resultados de busca", "Ferramentas para validar seu schema markup"], cta: "Implemente schema no seu site" },
  { day: 49, pillar: "P5", slug: "leads-estranhos-dentista-como-atrair", title: "Como Fazer Estranhos Quererem Agendar Com Você: A Ciência da Captação de Pacientes", targetKeyword: "captação pacientes odontológicos estratégia", category: "Captação", frameworkRef: "Hormozi $100M Leads: Core 4 lead generation methods", outline: ["Os 4 métodos fundamentais de captar pacientes", "Warm outreach: indicações sistematizadas", "Cold outreach: Google Ads e Meta Ads otimizados", "Content: blog, redes sociais, YouTube como ímã de pacientes", "Paid ads: investimento inteligente em tráfego", "Como escolher o método certo para seu momento", "O poder de combinar múltiplos canais"], cta: "Monte sua estratégia de captação" },

  // Days 50-63
  { day: 50, pillar: "P2", slug: "script-venda-consultorio-dentista", title: "Script de Venda Para Consultórios: Como Sua Equipe Pode Converter 2x Mais Agendamentos", targetKeyword: "script venda consultório dentista", category: "Conversão", problemRef: "2.3 No scripts for reception/assistants", outline: ["Por que improviso mata vendas no consultório", "Script de primeiro contato (WhatsApp)", "Script de agendamento (telefone)", "Script de follow-up (quando não responde)", "Script de objeção: 'vou pensar', 'está caro', 'vou pesquisar'", "Como treinar a equipe sem ser robótico", "Template completo para download"], cta: "Scripts prontos para sua equipe" },
  { day: 51, pillar: "P3", slug: "dados-mercado-odontologico-brasil-2025", title: "Mercado Odontológico Brasileiro em 2025: Dados, Tendências e Oportunidades", targetKeyword: "mercado odontológico Brasil 2025 dados", category: "Dados", outline: ["Número de dentistas no Brasil (e crescimento projetado)", "Faturamento médio por especialidade", "Cidades com maior demanda vs. maior oferta", "Procedimentos mais buscados no Google em 2024-2025", "Tendências de preço e ticket médio", "Onde estão as oportunidades inexploradas"], cta: "Análise do mercado na sua região" },
  { day: 52, pillar: "P1", slug: "como-medir-resultados-marketing-dentista", title: "Como Medir Resultados do Marketing Digital Para Dentistas: As 7 Métricas Que Importam", targetKeyword: "medir resultados marketing dentista métricas", category: "Dados", problemRef: "2.5 Poor tracking and attribution", outline: ["Por que 'curtidas' não pagam contas", "Métrica 1: CPL (custo por lead)", "Métrica 2: taxa de conversão lead → agendamento", "Métrica 3: taxa de comparecimento (show rate)", "Métrica 4: custo por paciente convertido", "Métrica 5: ticket médio por paciente", "Métrica 6: LTV (valor do paciente ao longo do tempo)", "Métrica 7: ROI por canal"], cta: "Dashboard de métricas para seu consultório" },
  { day: 53, pillar: "P4", slug: "marketing-clinica-odontologica-multiespecialidade", title: "Marketing Para Clínicas Multidisciplinares: Como Promover Múltiplas Especialidades Sem Diluir a Mensagem", targetKeyword: "marketing clínica odontológica multiespecialidade", category: "Estratégia", outline: ["O desafio: promover tudo = não promover nada", "Estratégia de 'serviço âncora': qual especialidade lidera", "Páginas dedicadas para cada especialidade (SEO)", "Campanhas separadas por serviço (Ads)", "Cross-sell inteligente: como um serviço leva a outro", "Google Maps: como categorizar uma clínica multi"], cta: "Estratégia para clínica multidisciplinar" },
  { day: 54, pillar: "P5", slug: "garantias-consultorio-odontologico-confianca", title: "Garantias Que Vendem: Como Remover o Medo do Paciente e Aumentar Conversão", targetKeyword: "garantia consultório odontológico conversão", category: "Conversão", frameworkRef: "Hormozi $100M Offers: Guarantees chapter", outline: ["Por que pacientes não agendam: medo é maior que desejo", "Tipos de garantia aplicáveis a odontologia", "Garantia de satisfação com o planejamento digital", "Garantia condicional: resultado ou continuamos sem custo", "Garantia implícita: pós-operatório assistido", "Como comunicar garantias sem prometer resultado clínico (CFO)", "O impacto na conversão: dados reais"], cta: "Implemente garantias inteligentes" },
  { day: 55, pillar: "P2", slug: "dentista-equipe-nao-funciona-como-resolver", title: "Sua Equipe Não Funciona? Como Alinhar Dentista, Recepção e Assistentes Para Crescer", targetKeyword: "equipe consultório odontológico treinamento", category: "Gestão", problemRef: "3.2 Internal Team Relationships / Staff not following scripts", outline: ["O impacto de uma equipe desalinhada no faturamento", "Recepção: o gargalo #1 de conversão", "Scripts e protocolos: criando processos que funcionam sem você", "Reuniões semanais de 15 minutos que transformam resultados", "Métricas de desempenho por pessoa", "Como criar accountability sem criar conflito"], cta: "Alinhe sua equipe" },
  { day: 56, pillar: "P1", slug: "google-ads-vs-seo-dentista-qual-melhor", title: "Google Ads vs. SEO Para Dentistas: Qual Investir Primeiro? (Análise Completa)", targetKeyword: "Google Ads vs SEO dentista qual melhor", category: "Estratégia", outline: ["A resposta curta: depende do seu momento", "Google Ads: resultado rápido, custo contínuo", "SEO: resultado demorado, retorno crescente", "Comparação por especialidade: quando cada um vence", "O cenário ideal: SEO + Ads trabalhando juntos", "Orçamento: como dividir entre os dois canais", "Timeline: expectativa realista de retorno para cada um"], cta: "Estratégia combinada de Ads + SEO" },
  { day: 57, pillar: "P3", slug: "perplexity-gemini-dentista-como-aparecer", title: "Perplexity e Gemini: As Novas Buscas de IA Onde Seu Consultório Precisa Aparecer", targetKeyword: "Perplexity Gemini dentista IA busca", category: "GEO", outline: ["Além do Google: como funciona Perplexity e Gemini", "O que diferencia cada plataforma de IA", "Como cada uma seleciona fontes e recomendações", "Otimizando para Perplexity: conteúdo estruturado + dados", "Otimizando para Gemini: entidade Google + Knowledge Graph", "Checklist: 5 ações para aparecer em todas as plataformas de IA"], cta: "Presença em IA para dentistas" },
  { day: 58, pillar: "P5", slug: "dentista-falar-linguagem-dinheiro", title: "Fale a Linguagem do Dinheiro: Como Dentistas de Sucesso Pensam Sobre Investimento em Marketing", targetKeyword: "dentista investimento marketing retorno", category: "Mentalidade", frameworkRef: "Kennedy Wealth Magnet 7: Speak Money / What You Speak Reveals What You Are", outline: ["A linguagem que separa dentistas que crescem dos que estagnam", "De 'custo de marketing' para 'investimento em aquisição de pacientes'", "De 'gastar com ads' para 'custo de aquisição com ROI mensurável'", "Como calcular o valor de cada paciente ao longo de 5 anos", "A conta que todo dentista deveria fazer antes de investir", "Mentalidade de investidor vs. mentalidade de poupador"], cta: "Pense como investidor" },

  // Days 59-70
  { day: 59, pillar: "P2", slug: "pacientes-so-querem-preco-como-lidar", title: "Pacientes Só Perguntam Preço? Como Mudar a Conversa Para Valor", targetKeyword: "paciente pergunta preço dentista como lidar", category: "Conversão", problemRef: "2.2 Leads looking only for budget quotes / 1.1 Having prices challenged", outline: ["Por que o lead pergunta preço: não é porque é 'fraco'", "O erro: responder com número imediatamente", "Técnica de redirecionamento: do preço para o valor", "Script: como responder 'quanto custa' no WhatsApp", "Como pré-qualificar na landing page antes do contato", "Posicionamento que atrai quem valoriza qualidade"], cta: "Converta leads de preço em pacientes" },
  { day: 60, pillar: "P4", slug: "marketing-dentista-clinico-geral", title: "Marketing Para Dentista Clínico Geral: Como Competir Quando Todos Oferecem o Mesmo", targetKeyword: "marketing dentista clínico geral diferenciação", category: "Clínico Geral", outline: ["O desafio do clínico geral: parecer 'mais do mesmo'", "Diferenciação: tecnologia, atendimento, experiência do paciente", "SEO local: dominando buscas genéricas na sua micro-região", "Google Maps: a arma secreta do clínico geral", "Conteúdo educativo: mostrando expertise em áreas específicas", "Cross-referral: parcerias com especialistas"], cta: "Diferencie sua clínica geral" },
  { day: 61, pillar: "P1", slug: "automacao-marketing-dentista-ferramentas", title: "Automação de Marketing Para Dentistas: 5 Ferramentas Que Trabalham Enquanto Você Atende", targetKeyword: "automação marketing dentista ferramentas", category: "Ferramentas", problemRef: "2.4 Manual processes → inefficiency", outline: ["O conceito: marketing que funciona sem você intervir", "Ferramenta 1: WhatsApp Business API + chatbot", "Ferramenta 2: Google Meu Negócio auto-posts", "Ferramenta 3: E-mail automatizado de reativação", "Ferramenta 4: CRM com pipeline automático", "Ferramenta 5: Agendamento online com lembretes", "Como integrar tudo sem complexidade"], cta: "Automatize seu marketing" },
  { day: 62, pillar: "P3", slug: "marketing-saude-digital-brasil-regulamentacao", title: "Marketing Digital Para Saúde no Brasil: Regulamentação, Ética e Oportunidades", targetKeyword: "marketing digital saúde Brasil regulamentação", category: "Compliance", outline: ["O cenário regulatório para saúde no Brasil", "CFO vs. CFM: diferenças para dentistas e médicos", "LGPD: como lidar com dados de pacientes", "Ética na publicidade de saúde: princípios universais", "O que outros países fazem (EUA, Portugal) e o que podemos aprender", "Oportunidades dentro do marco regulatório"], cta: "Marketing ético e efetivo" },
  { day: 63, pillar: "P5", slug: "dentista-oportunidade-mercado-como-aproveitar", title: "Oportunismo Estratégico: Como Dentistas Inteligentes Aproveitam Oportunidades Que Outros Ignoram", targetKeyword: "dentista oportunidade mercado crescimento", category: "Estratégia", frameworkRef: "Kennedy Wealth Magnet 4: Accepting Your Role / Are You Guilty of Opportunism?", outline: ["Oportunismo não é palavrão — é inteligência estratégica", "A oportunidade que 90% dos dentistas ignoram: presença em IA", "A oportunidade local: ser o primeiro a dominar o Google Maps no bairro", "A oportunidade de nicho: especializar quando todos generalizam", "A oportunidade de automação: escalar sem contratar", "Como identificar e agir em oportunidades antes dos concorrentes"], cta: "Identifique oportunidades na sua região" },

  // Days 64-77
  { day: 64, pillar: "P2", slug: "financiamento-tratamento-dentario-como-oferecer", title: "Financiamento de Tratamentos Dentários: Como Oferecer Sem Comprometer Seu Caixa", targetKeyword: "financiamento tratamento dentário consultório", category: "Gestão", problemRef: "Step C: Financiamento 12x as value multiplier", outline: ["O impacto do financiamento na conversão de high-ticket", "Modelos: parcelamento próprio vs. financeiras parceiras", "Como comunicar financiamento na landing page e WhatsApp", "O cálculo: margem vs. volume (quando compensa)", "Plataformas de financiamento para saúde no Brasil", "Scripts para apresentar financiamento sem parecer 'barato'"], cta: "Aumente conversão com financiamento" },
  { day: 65, pillar: "P1", slug: "conteudo-blog-dentista-o-que-escrever", title: "Blog Para Dentistas: 30 Ideias de Artigos Que Atraem Pacientes Via Google", targetKeyword: "blog dentista ideias artigos SEO", category: "Conteúdo", outline: ["Por que blog ainda funciona (e como usá-lo certo)", "10 artigos de 'o que é / como funciona' (informacional)", "10 artigos de 'preço / quanto custa' (comercial)", "10 artigos de 'melhor / perto de mim' (decisão)", "Estrutura ideal: H2s que viram respostas do Google", "Frequência: quantos artigos publicar por mês", "SEO on-page: checklist para cada artigo"], cta: "Gestão de conteúdo para dentistas" },
  { day: 66, pillar: "P4", slug: "marketing-dentista-rural-cidades-pequenas", title: "Marketing Para Dentistas em Cidades Pequenas: Estratégias Que Funcionam Fora das Capitais", targetKeyword: "marketing dentista cidade pequena interior", category: "Estratégia", outline: ["O cenário: menos concorrência digital, mais oportunidade", "Google Maps: dominando a região com facilidade", "SEO local em cidades pequenas: ranquear é mais rápido", "Instagram como canal principal em comunidades menores", "Parcerias locais: farmácias, escolas, empresas", "Google Ads com orçamento reduzido: quando compensa"], cta: "Marketing para cidades do interior" },
  { day: 67, pillar: "P5", slug: "dentista-sem-desculpas-crescimento", title: "Sem Desculpas: Por Que Nenhuma Justificativa Está Salvando Seu Consultório Da Estagnação", targetKeyword: "dentista crescimento consultório estagnação", category: "Mentalidade", frameworkRef: "Kennedy Wealth Magnet 6: No Excuses", outline: ["As desculpas mais comuns de dentistas que não crescem", "'Minha cidade é pequena demais'", "'Marketing não funciona para dentistas'", "'Já tentei e não deu certo'", "'Não tenho tempo para isso'", "'Meus pacientes são por indicação'", "Por que cada desculpa tem uma solução — e o primeiro passo"], cta: "Quebre o ciclo de estagnação" },
  { day: 68, pillar: "P2", slug: "parcerias-estrategicas-dentista-indicacoes", title: "Parcerias Estratégicas Para Dentistas: Como Criar Redes de Indicação Que Geram Pacientes", targetKeyword: "parcerias estratégicas dentista indicação referral", category: "Captação", problemRef: "3.3 Weak referral partnerships", outline: ["Indicação estruturada vs. indicação espontânea", "Parcerias com outros profissionais de saúde", "Parcerias com empresas (convênio corporativo)", "Programa de indicação para pacientes existentes", "Incentivos éticos para quem indica", "Como formalizar e rastrear parcerias"], cta: "Monte sua rede de parcerias" },
  { day: 69, pillar: "P1", slug: "seo-tecnico-consultorio-odontologico", title: "SEO Técnico Para Consultórios: 8 Ajustes No Seu Site Que o Google Adora", targetKeyword: "SEO técnico consultório odontológico site", category: "SEO", outline: ["O que é SEO técnico e por que importa", "Velocidade de carregamento (Core Web Vitals)", "Mobile-first: seu site funciona no celular?", "HTTPS e segurança", "Sitemap XML e robots.txt", "Schema markup para dentistas", "URLs amigáveis e estrutura de links", "Erros 404 e redirecionamentos"], cta: "Auditoria técnica do seu site" },
  { day: 70, pillar: "P3", slug: "video-marketing-dentista-youtube", title: "YouTube Para Dentistas: Como Criar Vídeos Que Atraem Pacientes (Sem Ser YouTuber)", targetKeyword: "YouTube dentista vídeos marketing", category: "Conteúdo", outline: ["Por que YouTube é a 2ª maior ferramenta de busca do mundo", "Tipos de vídeo que funcionam para dentistas (curtos, educativos)", "Equipamento mínimo: celular + luz + roteiro", "SEO no YouTube: título, descrição, tags para dentistas", "Compliance CFO em vídeos", "Como transformar 1 vídeo em 5 peças de conteúdo"], cta: "Estratégia de vídeo" },

  // Days 71-84
  { day: 71, pillar: "P2", slug: "dentista-nao-aparece-online-como-resolver", title: "Invisível Online? O Plano de 30 Dias Para Dentistas Que Não Aparecem em Nenhuma Busca", targetKeyword: "dentista não aparece Google como resolver", category: "Visibilidade", problemRef: "5. Feeling forgotten online", outline: ["Diagnóstico: por que você não aparece (e quem aparece)", "Semana 1: Google Meu Negócio otimizado", "Semana 2: site com SEO básico implementado", "Semana 3: primeiras avaliações e citações locais", "Semana 4: conteúdo publicado + Google Ads ativado", "O efeito acumulativo: de invisível para top 3 em 90 dias"], cta: "Saia da invisibilidade digital" },
  { day: 72, pillar: "P4", slug: "marketing-clinica-popular-baixo-custo", title: "Marketing Para Clínicas Populares: Como Captar Volume Sem Depender Só de Preço Baixo", targetKeyword: "marketing clínica popular odontológica", category: "Estratégia", outline: ["O modelo popular: volume + acessibilidade", "Diferenciação: não é só preço — é experiência", "Google Maps como canal principal para clínicas populares", "Anúncios com foco em acessibilidade e conveniência", "Operação eficiente: mais pacientes com menos ociosidade", "Fidelização: transformando primeira consulta em paciente recorrente"], cta: "Estratégia para clínica popular" },
  { day: 73, pillar: "P5", slug: "dentista-esteja-em-algum-lugar-presenca-digital", title: "Esteja Em Algum Lugar: Por Que Dentistas Invisíveis Online Estão Perdendo a Guerra", targetKeyword: "dentista presença digital importância", category: "Posicionamento", frameworkRef: "Kennedy Wealth Magnet 9: Be Somewhere", outline: ["O princípio: se as pessoas não te encontram, você não existe", "Os 5 'lugares' onde todo dentista precisa estar em 2025", "Google Maps: o mínimo viável", "Site otimizado: sua base digital", "Instagram: seu portfólio visual", "Plataformas de IA: o canal emergente", "Como priorizar: onde investir primeiro com orçamento limitado"], cta: "Construa sua presença digital" },
  { day: 74, pillar: "P1", slug: "retargeting-dentista-anuncios-remarketing", title: "Retargeting Para Dentistas: Como Alcançar Quem Visitou Seu Site Mas Não Agendou", targetKeyword: "retargeting remarketing dentista anúncios", category: "Ads", outline: ["O que é retargeting e por que funciona", "A estatística: 96% dos visitantes não convertem na primeira visita", "Como configurar retargeting no Meta Ads", "Como configurar retargeting no Google Ads", "Criativos de retargeting que convertem (depoimentos, urgência)", "Orçamento: quanto reservar para remarketing"], cta: "Implemente retargeting" },
  { day: 75, pillar: "P2", slug: "expectativa-paciente-resultado-como-gerenciar", title: "Gerenciamento de Expectativas: Como Evitar Avaliações Negativas e Pacientes Insatisfeitos", targetKeyword: "gerenciar expectativa paciente dentista avaliação", category: "Reputação", problemRef: "4.3 No expectation management → negative reviews", outline: ["Expectativas desalinhadas: a causa #1 de insatisfação", "O momento certo para alinhar: antes do procedimento", "Técnicas de comunicação: visual, escrita, verbal", "Template de consentimento informado (além do padrão)", "Follow-up pós-procedimento: prevenindo reclamações", "Como responder quando algo dá errado"], cta: "Previna avaliações negativas" },
  { day: 76, pillar: "P3", slug: "lgpd-consultorio-odontologico-dados-pacientes", title: "LGPD Para Consultórios Odontológicos: O Que Você Precisa Saber Sobre Dados de Pacientes", targetKeyword: "LGPD consultório odontológico dados pacientes", category: "Compliance", outline: ["O que é LGPD e como impacta consultórios", "Dados que você coleta (e precisa proteger)", "Consentimento: como obter e documentar", "WhatsApp e marketing: o que a LGPD diz", "CRM e banco de dados: requisitos de segurança", "Penalidades: o que acontece se violar"], cta: "Adeque seu consultório à LGPD" },
  { day: 77, pillar: "P5", slug: "dentista-acao-supera-perfeicao", title: "Pare de Planejar, Comece a Executar: Por Que Ação Supera Perfeição no Marketing Odontológico", targetKeyword: "dentista marketing ação execução começar", category: "Mentalidade", frameworkRef: "Kennedy Wealth Magnet 10: Do Something", outline: ["O inimigo #1 do crescimento: paralisia por análise", "Por que dentistas perfeccionistas ficam para trás", "O conceito de 'bom o suficiente' no marketing", "As 3 ações mais impactantes que você pode fazer HOJE", "Google Meu Negócio: 30 minutos para otimizar", "WhatsApp: 1 template para enviar a todos os leads", "O efeito composto de ações imperfeitas mas consistentes"], cta: "Comece hoje — diagnóstico gratuito" },

  // Days 78-90
  { day: 78, pillar: "P1", slug: "analise-concorrencia-dentista-ferramentas", title: "Análise de Concorrência Para Dentistas: Ferramentas Gratuitas Para Espiar o Marketing do Rival", targetKeyword: "análise concorrência dentista ferramentas", category: "Ferramentas", outline: ["Por que monitorar concorrentes é essencial", "Google Maps: analisando perfil dos concorrentes", "Facebook Ad Library: vendo os anúncios deles", "SEO: ferramentas gratuitas para ver ranking", "Google Alerts: monitorando menções", "O que fazer com as informações: aplicação prática"], cta: "Análise competitiva da sua região" },
  { day: 79, pillar: "P2", slug: "sazonalidade-odontologia-como-manter-faturamento", title: "Sazonalidade na Odontologia: Como Manter o Faturamento Estável o Ano Todo", targetKeyword: "sazonalidade odontologia faturamento estável", category: "Gestão", problemRef: "2.1 High seasonality impacting monthly cashflow", outline: ["Os meses fortes e fracos da odontologia no Brasil", "Estratégias para meses fracos: promoções, reativação, conteúdo", "Planejamento de campanha por trimestre", "Como suavizar a curva com pacientes recorrentes", "Programa de manutenção semestral como receita previsível", "Marketing antecipado: preparar o pipeline antes da baixa"], cta: "Estabilize seu faturamento" },
  { day: 80, pillar: "P4", slug: "marketing-dentista-idoso-geriatria", title: "Marketing Para Odontogeriatria: Como Alcançar Pacientes Idosos e Seus Familiares", targetKeyword: "marketing odontogeriatria pacientes idosos", category: "Odontogeriatria", outline: ["O envelhecimento do Brasil: oportunidade para odontologia", "Quem decide: o idoso ou o familiar?", "Canais: Google (familiar busca) + indicação (tradicional)", "Conteúdo empático: dignidade, conforto, cuidado", "Acessibilidade: comunicação clara e direta", "Parcerias com geriátras e casas de repouso"], cta: "Estratégia para público sênior" },
  { day: 81, pillar: "P5", slug: "integridade-marketing-dentista-confianca", title: "Integridade Como Estratégia de Marketing: Por Que Dentistas Honestos Crescem Mais", targetKeyword: "integridade marketing dentista confiança", category: "Posicionamento", frameworkRef: "Kennedy Wealth Magnet 13: Integrity", outline: ["Integridade não é obstáculo — é vantagem competitiva", "Como transparência gera mais confiança que marketing agressivo", "Preço justo e comunicação honesta como diferencial", "Avaliações reais: a prova que vem da integridade", "Compliance CFO como demonstração de profissionalismo", "O efeito longo prazo: reputação composta"], cta: "Marketing com integridade" },
  { day: 82, pillar: "P1", slug: "google-ads-palavras-chave-negativas-dentista", title: "Palavras-Chave Negativas Para Dentistas: A Lista Que Pode Economizar R$1.000/Mês em Ads", targetKeyword: "palavras-chave negativas Google Ads dentista", category: "Ads", outline: ["O que são palavras-chave negativas e por que são críticas", "A lista completa para odontologia (50+ termos)", "Negativas universais: emprego, curso, faculdade, gratuito", "Negativas por especialidade", "Como revisar termos de busca semanalmente", "Impacto: redução de 20-40% no CPL"], cta: "Auditoria de palavras-chave dos seus Ads" },
  { day: 83, pillar: "P2", slug: "programa-fidelidade-dentista-retencao-pacientes", title: "Programa de Fidelidade Para Consultórios: Como Transformar Pacientes em Fãs Que Voltam e Indicam", targetKeyword: "programa fidelidade dentista retenção pacientes", category: "Retenção", problemRef: "4.4 No VIP programs", outline: ["O custo de adquirir vs. reter um paciente (5x mais caro)", "Programa de manutenção semestral com benefícios", "Programa VIP: descontos progressivos + prioridade", "Programa de indicação com recompensa ética", "Automação: lembretes, parabéns, datas especiais", "Como medir retenção e lifetime value"], cta: "Crie seu programa de fidelidade" },
  { day: 84, pillar: "P3", slug: "futuro-odontologia-digital-2025-2030", title: "O Futuro da Odontologia Digital: O Que Esperar de 2025 a 2030", targetKeyword: "futuro odontologia digital 2025 2030", category: "Tendências", outline: ["IA no diagnóstico e planejamento", "Teleodontologia: consultas remotas", "Impressão 3D: próteses e guias cirúrgicos", "Marketing automatizado por IA", "Busca por voz e IA conversacional", "Personalização de tratamento via dados", "O que dentistas devem fazer AGORA para se preparar"], cta: "Prepare-se para o futuro" },
  { day: 85, pillar: "P1", slug: "citacoes-locais-dentista-nap", title: "Citações Locais Para Dentistas: O Que São, Por Que Importam e Como Construir", targetKeyword: "citações locais NAP dentista SEO", category: "SEO", outline: ["O que são citações locais (NAP consistency)", "Por que o Google usa citações como fator de ranqueamento", "Os 10 diretórios mais importantes para dentistas no Brasil", "Como criar e manter citações consistentes", "Ferramentas para monitorar citações", "O impacto de citações inconsistentes"], cta: "Construa suas citações locais" },
  { day: 86, pillar: "P4", slug: "marketing-dentista-atm-disfuncao-temporomandibular", title: "Marketing Para ATM/DTM: Como Captar Pacientes Com Disfunção Temporomandibular", targetKeyword: "marketing DTM ATM dentista", category: "ATM/DTM", outline: ["O paciente de DTM: dor crônica e busca por solução", "Palavras-chave: bruxismo, dor mandíbula, estalar mandíbula", "Conteúdo educativo como funil (paciente não sabe que precisa de dentista)", "Google Ads para sintomas vs. tratamentos", "Parcerias com fisioterapeutas e neurologistas", "Posicionamento como especialista em DTM na região"], cta: "Capte pacientes de DTM" },
  { day: 87, pillar: "P5", slug: "dentista-prova-social-como-construir", title: "Prova Social Para Dentistas: 7 Formas de Mostrar Que Seu Consultório É a Melhor Escolha", targetKeyword: "prova social dentista consultório", category: "Conversão", frameworkRef: "Hormozi $100M Leads: Social proof as lead magnet / Kennedy: Demonstration", outline: ["O princípio: pessoas seguem o que outros aprovam", "Forma 1: Avaliações Google (volume + qualidade)", "Forma 2: Depoimentos em vídeo (com consentimento)", "Forma 3: Números e métricas (pacientes atendidos, anos de experiência)", "Forma 4: Certificações e formações visíveis", "Forma 5: Prêmios e reconhecimentos", "Forma 6: Presença na mídia e parcerias", "Forma 7: Conteúdo de bastidores (transparência)"], cta: "Construa sua prova social" },
  { day: 88, pillar: "P2", slug: "whatsapp-paciente-nao-responde-como-recuperar", title: "Lead Não Responde no WhatsApp? 5 Estratégias Para Recuperar Pacientes Que Sumiram", targetKeyword: "lead WhatsApp não responde dentista recuperar", category: "Conversão", problemRef: "2.2 Leads who don't respond on WhatsApp", outline: ["Por que leads param de responder (e não é falta de interesse)", "Erro #1: mensagem genérica sem personalização", "Estratégia 1: mensagem de valor (não de cobrança)", "Estratégia 2: prova social oportuna", "Estratégia 3: lembrete com prazo", "Estratégia 4: mudança de canal (ligação, SMS)", "Estratégia 5: campanha de reengajamento via ads", "Templates prontos para cada estratégia"], cta: "Recupere seus leads perdidos" },
  { day: 89, pillar: "P3", slug: "marketing-odontologico-portugal-expansao", title: "Marketing Odontológico em Portugal: Oportunidades Para Dentistas Brasileiros", targetKeyword: "marketing odontológico Portugal dentista brasileiro", category: "Internacional", outline: ["O mercado odontológico português: visão geral", "Diferenças regulatórias: CFO vs. Ordem dos Médicos Dentistas", "SEO local em Portugal: Google.pt e peculiaridades", "Oportunidade: poucos dentistas investem em marketing digital", "Como adaptar estratégias brasileiras para Portugal", "A LK Digital em Portugal: como atendemos"], cta: "Marketing para dentistas em Portugal" },
  { day: 90, pillar: "P1", slug: "checklist-completo-marketing-digital-dentista", title: "O Checklist Definitivo de Marketing Digital Para Dentistas: 50 Ações Para Agenda Cheia", targetKeyword: "checklist marketing digital dentista completo", category: "Guia", outline: ["Presença digital básica (10 ações)", "SEO local e Google Maps (10 ações)", "Conteúdo e redes sociais (10 ações)", "Anúncios pagos (10 ações)", "Conversão e retenção (10 ações)", "Download: PDF do checklist completo"], cta: "Baixe o checklist e comece agora" },
];

// Helper: get posts by pillar
export function getPostsByPillar(pillar: ContentCalendarEntry["pillar"]) {
  return contentCalendar.filter((p) => p.pillar === pillar);
}

// Helper: get post by day
export function getPostByDay(day: number) {
  return contentCalendar.find((p) => p.day === day);
}
